---
apiVersion: v1
kind: Namespace
metadata:
  name: whoami-limited
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: whoami-limited
  name: whoami-limited
spec:
  replicas: 4
  selector:
    matchLabels:
      app: whoami-limited
  template:
    metadata:
      labels:
        app: whoami-limited
    spec:
      containers:
        - image: docker.io/containous/whoami
          imagePullPolicy: IfNotPresent
          name: whoami-limited
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
