---
apiVersion: v1
kind: Pod
metadata:
  name: httpbin
spec:
  containers:
    - image: docker.io/kennethreitz/httpbin
      imagePullPolicy: IfNotPresent
      name: httpbin
      ports:
        - containerPort: 80
